import { makeStyles } from '@material-ui/core/styles';
import type { Theme } from '@material-ui/core/styles';
import { fontBody, fontDisplay, fontMono, type HangarTokens } from '../brand/tokens';

// The plugin's shared look, taken from the Environments mockup (board F of the design canvas): flat panels with a
// 1px line and a 6px radius, mono uppercase labels, condensed display type for names and titles, one amber primary
// button, and small bordered chips for tier and state. Every tab used to redeclare these with slightly different
// numbers (titles of 14.5, 15, 16 and 20px; primary buttons with three different inks); new UI uses this kit and
// older tabs move onto it. See docs/design-system.md.
export const useUi = makeStyles<Theme, { t: HangarTokens }>(() => ({
  // ---- page chrome
  pageHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 16, flexWrap: 'wrap', marginBottom: 14 },
  pageTitle: { margin: 0, fontFamily: fontDisplay, fontWeight: 700, fontSize: 26, lineHeight: 1.1, color: ({ t }) => t.textHi },
  pageSub: { margin: '4px 0 0', fontFamily: fontBody, fontSize: 13, color: ({ t }) => t.textLo },
  pageActions: { display: 'flex', gap: 8, alignItems: 'center' },
  // ---- surfaces
  panel: { backgroundColor: ({ t }) => t.panel, border: ({ t }) => `1px solid ${t.line}`, borderRadius: 6 },
  panelAccent: { borderColor: ({ t }) => t.amberLine },
  sectionLabel: {
    margin: 0,
    fontFamily: fontMono,
    fontWeight: 600,
    fontSize: 11,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: ({ t }) => t.textLo,
  },
  columnLabel: {
    fontFamily: fontMono,
    fontWeight: 500,
    fontSize: 10.5,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: ({ t }) => t.textLo,
  },
  // ---- controls
  button: {
    fontFamily: fontBody,
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1.2,
    padding: '7px 13px',
    borderRadius: 5,
    border: ({ t }) => `1px solid ${t.line}`,
    backgroundColor: ({ t }) => t.panelAlt,
    color: ({ t }) => t.textHi,
    cursor: 'pointer',
    '&:hover:not(:disabled)': { borderColor: ({ t }) => t.textFaint },
    '&:disabled': { opacity: 0.45, cursor: 'default' },
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 1 },
  },
  buttonPrimary: {
    backgroundColor: ({ t }) => t.amber,
    borderColor: ({ t }) => t.amber,
    color: ({ t }) => t.onAmber,
    fontWeight: 600,
    '&:hover:not(:disabled)': { borderColor: ({ t }) => t.amber, filter: 'brightness(1.08)' },
  },
  buttonDanger: { backgroundColor: 'transparent', borderColor: ({ t }) => t.bad, color: ({ t }) => t.bad, '&:hover:not(:disabled)': { borderColor: ({ t }) => t.bad } },
  buttonSmall: { padding: '4px 9px', fontSize: 12 },
  iconButton: {
    width: 28,
    height: 28,
    display: 'inline-grid',
    placeItems: 'center',
    padding: 0,
    border: ({ t }) => `1px solid ${t.line}`,
    borderRadius: 4,
    backgroundColor: 'transparent',
    color: ({ t }) => t.textLo,
    fontFamily: fontMono,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    '&:hover:not(:disabled)': { color: ({ t }) => t.textHi, borderColor: ({ t }) => t.textFaint },
    '&:disabled': { opacity: 0.35, cursor: 'default' },
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 1 },
  },
  // ---- chips
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontFamily: fontMono,
    fontWeight: 500,
    fontSize: 11,
    lineHeight: 1,
    padding: '4px 7px',
    border: ({ t }) => `1px solid ${t.line}`,
    borderRadius: 4,
    color: ({ t }) => t.textLo,
    whiteSpace: 'nowrap',
  },
  chipGround: { color: ({ t }) => t.sky, borderColor: ({ t }) => t.skyLine },
  chipFlight: { color: ({ t }) => t.amber, borderColor: ({ t }) => t.amberLine },
  chipOk: { color: ({ t }) => t.good, borderColor: ({ t }) => t.good },
  chipBad: { color: ({ t }) => t.bad, borderColor: ({ t }) => t.bad },
  // ---- sub-tabs inside a panel
  subtabs: { display: 'flex', gap: 2, borderBottom: ({ t }) => `1px solid ${t.line}` },
  subtab: {
    fontFamily: fontDisplay,
    fontWeight: 600,
    fontSize: 13,
    padding: '9px 14px',
    marginBottom: -1,
    border: 0,
    borderBottom: '2px solid transparent',
    backgroundColor: 'transparent',
    color: ({ t }) => t.textLo,
    cursor: 'pointer',
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: -2 },
  },
  marker: { display: 'inline-block', width: 6, height: 6, borderRadius: '50%', marginLeft: 6, verticalAlign: 'middle', backgroundColor: ({ t }) => t.amber },
  sideBySide: { display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 350px', gap: 18, alignItems: 'start' },
  subtabOn: { color: ({ t }) => t.textHi, borderBottomColor: ({ t }) => t.amber },
  // ---- status
  dot: { width: 8, height: 8, borderRadius: '50%', display: 'inline-block', flexShrink: 0 },
  // ---- form fields
  field: { display: 'flex', flexDirection: 'column', gap: 5, minWidth: 0 },
  fieldLabel: { display: 'flex', justifyContent: 'space-between', gap: 8, fontFamily: fontBody, fontSize: 12, fontWeight: 500, color: ({ t }) => t.textLo },
  fieldSource: { fontFamily: fontMono, fontSize: 10, letterSpacing: '0.06em', textTransform: 'uppercase', color: ({ t }) => t.textLo },
  fieldSourceSet: { color: ({ t }) => t.sky },
  input: {
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: ({ t }) => t.bg,
    border: ({ t }) => `1px solid ${t.line}`,
    borderRadius: 4,
    color: ({ t }) => t.textHi,
    padding: '8px 10px',
    fontFamily: fontMono,
    fontSize: 13,
    '&::placeholder': { fontFamily: fontBody, fontStyle: 'italic', color: ({ t }) => t.textFaint, opacity: 0.85 },
    '&:focus': { outline: 'none', borderColor: ({ t }) => t.amber },
  },
  formSection: { borderTop: ({ t }) => `1px solid ${t.line}`, paddingTop: 14, marginTop: 14 },
  formSectionTitle: { margin: '0 0 10px', fontFamily: fontDisplay, fontWeight: 600, fontSize: 14, color: ({ t }) => t.textHi },
  note: { fontSize: 12.5, color: ({ t }) => t.textLo },
  problem: { fontSize: 12.5, color: ({ t }) => t.bad },
}));

// Filters, search and text links. A separate hook: makeStyles with function values builds every rule per hook call,
// so the controls only some views use do not make every Button, Chip and Panel pay for them.
export const useControls = makeStyles<Theme, { t: HangarTokens }>(() => ({
  // ---- filters: what a view shows. Separate pills (the Pipelines tab's History look); the one that is on is amber.
  // Never used for an action: an action is a `button` (it changes something), a filter only changes the view.
  filterBar: { display: 'flex', alignItems: 'center', gap: '10px 18px', flexWrap: 'wrap', marginBottom: 14 },
  filterBarEnd: { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' },
  filterGroup: { display: 'inline-flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  filterLabel: { fontFamily: fontBody, fontSize: 12, color: ({ t }) => t.textFaint, marginRight: 2 },
  filterChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    fontFamily: fontMono,
    fontWeight: 500,
    fontSize: 11,
    lineHeight: 1.2,
    padding: '5px 10px',
    borderRadius: 6,
    border: ({ t }) => `1px solid ${t.line}`,
    backgroundColor: ({ t }) => t.panel,
    color: ({ t }) => t.textLo,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    '&:hover:not(:disabled)': { borderColor: ({ t }) => t.textFaint, color: ({ t }) => t.textHi },
    '&:disabled': { opacity: 0.45, cursor: 'default' },
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 1 },
  },
  filterChipOn: {
    borderColor: ({ t }) => t.amberLine,
    backgroundColor: ({ t }) => t.amberSoft,
    color: ({ t }) => t.amberInk,
    '&:hover:not(:disabled)': { borderColor: ({ t }) => t.amber, color: ({ t }) => t.amberInk },
  },
  filterCount: { color: ({ t }) => t.textFaint },
  filterCountOn: { color: ({ t }) => t.amberInk, opacity: 0.75 },
  select: {
    fontFamily: fontMono,
    fontWeight: 500,
    fontSize: 11,
    lineHeight: 1.2,
    padding: '5px 8px',
    borderRadius: 6,
    border: ({ t }) => `1px solid ${t.line}`,
    backgroundColor: ({ t }) => t.panel,
    color: ({ t }) => t.textHi,
    cursor: 'pointer',
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 1 },
  },
  search: { position: 'relative', display: 'flex', alignItems: 'center', flex: '1 1 240px', minWidth: 200 },
  searchIcon: { position: 'absolute', left: 10, fontSize: '16px !important', color: ({ t }) => t.textFaint, pointerEvents: 'none' },
  searchInput: {
    width: '100%',
    boxSizing: 'border-box',
    fontFamily: fontBody,
    fontSize: 13,
    padding: '6px 10px 6px 32px',
    borderRadius: 6,
    border: ({ t }) => `1px solid ${t.line}`,
    backgroundColor: ({ t }) => t.panel,
    color: ({ t }) => t.textHi,
    '&::placeholder': { color: ({ t }) => t.textFaint },
    '&:focus': { outline: 'none', borderColor: ({ t }) => t.amber },
  },
  // ---- links: go somewhere (another tab, another site) or show/hide a detail. Text, never a box.
  textLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    fontFamily: fontMono,
    fontSize: 12,
    color: ({ t }) => t.sky,
    background: 'none',
    border: 0,
    padding: 0,
    cursor: 'pointer',
    textDecoration: 'none',
    '&:hover': { textDecoration: 'underline' },
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 2 },
  },
}));

// Status chips: what state something is in. Rounded (a label chip is square), a soft tint of the state's colour.
// Its own hook for the same reason as useControls.
export const useStatus = makeStyles<Theme, { t: HangarTokens }>(() => ({
  status: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontFamily: fontMono,
    fontWeight: 500,
    fontSize: 11,
    lineHeight: 1.3,
    padding: '2px 9px',
    borderRadius: 11,
    border: '1px solid',
    whiteSpace: 'nowrap',
  },
  statusButton: {
    cursor: 'pointer',
    '&:hover': { filter: 'brightness(0.97)' },
    '&:focus-visible': { outline: ({ t }) => `2px solid ${t.amber}`, outlineOffset: 1 },
  },
  statusDot: { width: 6, height: 6, borderRadius: '50%', backgroundColor: 'currentColor', flexShrink: 0 },
  ok: { color: ({ t }) => t.good, backgroundColor: ({ t }) => t.goodSoft, borderColor: ({ t }) => t.good },
  warn: { color: ({ t }) => t.amberInk, backgroundColor: ({ t }) => t.amberSoft, borderColor: ({ t }) => t.amberLine },
  bad: { color: ({ t }) => t.bad, backgroundColor: ({ t }) => t.badSoft, borderColor: ({ t }) => t.bad },
  info: { color: ({ t }) => t.sky, backgroundColor: ({ t }) => t.skySoft, borderColor: ({ t }) => t.skyLine },
  neutral: { color: ({ t }) => t.textLo, backgroundColor: ({ t }) => t.panelAlt, borderColor: ({ t }) => t.line },
}));
