// Shared raw Kubernetes-API-proxy helpers, factored out of
// tekton/useTektonPipelineRuns.ts once a second consumer (useAnalysisRuns.ts)
// needed the exact same "go straight at the generic proxy, not
// useCustomResources" mechanism - see that file's own comment for the full
// reasoning: useCustomResources(entity, [...]) resolves objects through the
// entity's `hangar.io/app=<name>` label-selector, and both Tekton
// PipelineRuns and Argo Rollouts' own AnalysisRun child resources are
// generated by their respective controllers without that label at all
// (confirmed live on both). Going straight at
// `/api/kubernetes/proxy/<k8s-api-path>` + a `Backstage-Kubernetes-Cluster`
// header - the same route kubernetesProxyApiRef.getPodLogs itself calls
// under the hood - sidesteps label-selector matching entirely.

export async function k8sProxyGet<T>(
  discoveryApi: { getBaseUrl(id: string): Promise<string> },
  fetchApi: { fetch: typeof fetch },
  clusterName: string,
  path: string,
): Promise<T> {
  const baseUrl = await discoveryApi.getBaseUrl('kubernetes');
  const res = await fetchApi.fetch(`${baseUrl}/proxy${path}`, {
    headers: { 'Backstage-Kubernetes-Cluster': clusterName },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => undefined);
    throw new Error(body?.error?.message ?? body?.message ?? `request failed with ${res.status}`);
  }
  return res.json() as Promise<T>;
}

// Write counterpart to k8sProxyGet - same generic Kubernetes-proxy route (a
// raw passthrough to whichever cluster's API server the caller names), just
// a POST with a JSON body instead of a GET. Added for Tower's Tekton
// "Re-run" action (useRerunPipelineRun.ts): unlike every other consumer of
// this proxy so far, that one needs to actually create an object, not just
// read one, which only works because the target cluster's RBAC for this
// identity has a scoped `create` grant on the one resource kind involved
// (gitops-cluster-dev's backstage-ingestor-rbac/rbac.yaml,
// `backstage-tekton-rerun` ClusterRole) - see that file's own comment for
// why this stayed a single-verb addition to the existing read-only identity
// rather than a second ServiceAccount/token.
export async function k8sProxyPost<T>(
  discoveryApi: { getBaseUrl(id: string): Promise<string> },
  fetchApi: { fetch: typeof fetch },
  clusterName: string,
  path: string,
  body: unknown,
): Promise<T> {
  const baseUrl = await discoveryApi.getBaseUrl('kubernetes');
  const res = await fetchApi.fetch(`${baseUrl}/proxy${path}`, {
    method: 'POST',
    headers: { 'Backstage-Kubernetes-Cluster': clusterName, 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const responseBody = await res.json().catch(() => undefined);
    throw new Error(responseBody?.error?.message ?? responseBody?.message ?? `request failed with ${res.status}`);
  }
  return res.json() as Promise<T>;
}

// Second write counterpart, for Tower's Tekton "Cancel" action
// (useCancelPipelineRun.ts) - a merge-patch instead of a POST, since
// cancelling means changing one field (spec.status) on the EXISTING
// PipelineRun rather than creating a new object. Content-Type
// application/merge-patch+json is what tells the API server to interpret
// the body as a merge patch rather than a full replace; the same
// `backstage-tekton-rerun` ClusterRole's `patch` verb (added alongside
// `create` - see that role's own comment on why this stayed a single
// identity) is what authorizes this.
export async function k8sProxyPatch<T>(
  discoveryApi: { getBaseUrl(id: string): Promise<string> },
  fetchApi: { fetch: typeof fetch },
  clusterName: string,
  path: string,
  body: unknown,
): Promise<T> {
  const baseUrl = await discoveryApi.getBaseUrl('kubernetes');
  const res = await fetchApi.fetch(`${baseUrl}/proxy${path}`, {
    method: 'PATCH',
    headers: { 'Backstage-Kubernetes-Cluster': clusterName, 'Content-Type': 'application/merge-patch+json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const responseBody = await res.json().catch(() => undefined);
    throw new Error(responseBody?.error?.message ?? responseBody?.message ?? `request failed with ${res.status}`);
  }
  return res.json() as Promise<T>;
}

// Same proxy route, for the one endpoint that doesn't return JSON - a pod's
// raw log text. `kubernetesProxyApiRef.getPodLogs` (the typed wrapper the
// rest of Tower uses, e.g. PodLogsView) doesn't expose a `timestamps`
// option, and useTaskRunLogs.ts needs real per-line timestamps to
// interleave and label a TaskRun's steps in one consolidated view - going
// straight at the same proxy route with `?timestamps=true` gets that
// directly from the Kubernetes API rather than trying to reconstruct it.
export async function k8sProxyGetText(
  discoveryApi: { getBaseUrl(id: string): Promise<string> },
  fetchApi: { fetch: typeof fetch },
  clusterName: string,
  path: string,
): Promise<string> {
  const baseUrl = await discoveryApi.getBaseUrl('kubernetes');
  const res = await fetchApi.fetch(`${baseUrl}/proxy${path}`, {
    headers: { 'Backstage-Kubernetes-Cluster': clusterName },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => undefined);
    throw new Error(body?.error?.message ?? body?.message ?? `request failed with ${res.status}`);
  }
  return res.text();
}
